version: "3.9"

name: classified-adversitments

services:
  rabbitmq:
    image: masstransit/rabbitmq:3.9.7
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure

  redis:
    image: redis:7.2.2-alpine3.18
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - 63790:6379
    restart: on-failure
    volumes:
      - type: volume
        source: redis-data-volume
        target: /data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
    restart: on-failure

  identity-postgresql:
    image: postgres:15.4-bullseye
    container_name: identity-postgresql
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "ClassifiedAdvertisiments123!"
    ports:
      - 54320:5432
    restart: on-failure
    volumes:
      - type: volume
        source: identity-postgresql-data-volume
        target: /var/lib/postgresql/data

  ads-command-postgresql:
    image: postgres:15.4-bullseye
    container_name: ads-command-postgresql
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "ClassifiedAdvertisiments123!"
    ports:
      - 54321:5432
    restart: on-failure
    volumes:
      - type: volume
        source: ads-command-postgresql-data-volume
        target: /var/lib/postgresql/data

  ads-query-postgresql:
    image: postgres:15.4-bullseye
    container_name: ads-query-postgresql
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "ClassifiedAdvertisiments123!"
    ports:
      - 54322:5432
    restart: on-failure
    volumes:
      - type: volume
        source: ads-query-postgresql-data-volume
        target: /var/lib/postgresql/data

  users-postgresql:
    image: postgres:15.4-bullseye
    container_name: users-postgresql
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "ClassifiedAdvertisiments123!"
    ports:
      - 54323:5432
    restart: on-failure
    volumes:
      - type: volume
        source: users-postgresql-data-volume
        target: /var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis-data-volume:
    driver: local
  identity-postgresql-data-volume:
    driver: local
  ads-command-postgresql-data-volume:
    driver: local
  ads-query-postgresql-data-volume:
    driver: local
  users-postgresql-data-volume:
    driver: local
