version: "3.9"

name: classified-adversitments

services:
  rabbitmq:
    image: masstransit/rabbitmq:3.9.7
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure

  redis:
    image: redis:7.2.2-alpine3.18
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - 63790:6379
    restart: on-failure
    volumes:
      - type: volume
        source: redis-data
        target: /data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
    restart: on-failure

  identity-postgresql:
    image: postgres:15.4-bullseye
    container_name: identity-postgresql
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "ClassifiedAdvertisiments123!"
    ports:
      - 54320:5432
    restart: on-failure

  ads-command-eventstore:
    container_name: ads-command-eventstore
    image: eventstore/eventstore:22.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 1113:1113
      - 2113:2113
    restart: on-failure
    volumes:
      - type: volume
        source: ads-command-eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: ads-command-eventstore-volume-logs
        target: /var/log/eventstore

  ads-query-mongodb:
    image: mongo:7.0.0-rc3-jammy
    container_name: ads-query-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
    restart: on-failure
    volumes:
      - "ads-query-mongodb-data-volume:/data/db"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis-data:
    driver: local
  ads-command-eventstore-volume-data:
    driver: local
  ads-command-eventstore-volume-logs:
    driver: local
  ads-query-mongodb-data-volume:
    driver: local
